version: '3.8'

services:
  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: conexa
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://user:secretpassword@postgres:5432/conexa
    depends_on:
      - postgres

volumes:
  postgres_data:
